- op: replace
  path: /data
  value:
    service.slack: |
      token: $slack-token
    trigger.on-sync-running: |
      - description: Application is being synced
        send:
        - app-sync-running
        when: app.status.operationState.phase in ['Running']

    trigger.on-sync-succeeded: |-
      - description: Application syncing has succeeded
        send:
        - app-sync-succeeded
        when: app.status.operationState.phase in ['Succeeded']