apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "jarvis-test"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "jarvis-test"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: cluster-config/overlays
    repoURL: https://github.com/StinkyBenji/openshift-gitops-practice
    targetRevision: master
