apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd-01
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "jarvis-test"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "jarvis-test"
spec:
  destination:
    namespace: argocd-01            
    server: https://kubernetes.default.svc
  project: root-app
  source:
    path: argocd/apps/vplugin-test
    repoURL: https://github.com/StinkyBenji/openshift-gitops-practice
    targetRevision: master
    
  