kind: Secret
apiVersion: v1
metadata:
  namespace: argocd-01
  name: argocd-notifications-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/vplugin/slacktoken"
type: Opaque
stringData:
  slack-token: <slack-token>